### ISSUE TITLE
[Activities Configurator]: Not work on Ubuntu 17.10 gnome 3.26

### ISSUE THREAD

**Issue by sandangel** [nls1729/acme-code#29] opened 2017-10-17 01:48 UTC
I tried to install from the web as web as from .zip file but it's not work, any fix?

**Comment by nls1729** [comment] 2017-10-17 19:58
Ubuntu 17.10 is using a patched version of the Gnome Shell.  From reading various items on the Internet I found the Ubuntu developers wanted a means to disable the Hot Corner in the Gnome Shell.  A patch was provided by a Gnome developer and was applied by the Ubuntu developers to Gnome Shell version 3.26 used in Ubuntu. The patch provides a means to disable the Hot Corner.  The method used in the patch disables the Hot Corner in a way that causes the Activities Configurator to error when installed.

Apparently the Ubuntu developers have a reason to remove the Hot Corner. I can't maintain the extension to operate properly if the Ubuntu Gnome Shell is different from the Gnome Shell provided in other Linux distributions.  There is no fix.

**Comment by nls1729** [comment] 2017-10-22 17:00
I have tested Ubuntu 17.10 running a vanilla Gnome Shell session.
The extension appears to function normally under GNOME.  You may want
to try the GNOME session under 17.10.

Please see http://preview.tinyurl.com/yadxwokc

**Comment by Maestroschan** [comment] 2017-10-27 21:06
if you re-enable the hot-corner during extension initialisation, could it work ?

something like "if the gsettings key org.gnome.shell enable-hot-corners exists, then set its boolean at true" ?

**Comment by nls1729** [comment] 2017-10-28 10:59
Hello,

> if you re-enable the hot-corner during extension initialisation, could it work ?

Yes and no.  The Gnome Shell has been altered by the Ubuntu developers to provide
"a Unity like experience".  Changes to the shell for this experience interfere with
the Activities Configurator.  The Hot Corner is missing, the theme is changed and
App Indicators are provided.  The current version of the extension errors on enable
after it is installed.  It can be enabled with 'dconf Editor' by changing the setting
of /org/gnome/shell/enable-hot-corners to True.  I recommend you DO NOT use the
Ubuntu session with the Hot Corners enabled.  Several options of the extension are
very broken under the Ubuntu session.

An option is to install the standard Gnome Shell to get access to the GNOME session.
See  "How To Install Vanilla GNOME Shell on Ubuntu 17.10" at:
http://www.omgubuntu.co.uk/2017/10/install-vanilla-gnome-shell-ubuntu-17-10

Ubuntu running in a GNOME session allows not only the Activities Configurator to
function properly but other extensions will not be broken.

I am currently working on the Activities Configurator code to detect and handle
the Ubuntu session and/or missing hot corners without creating an error on enable.

I will leave this issue open until the new version of the extension is available.

Regards,
Norman

**Comment by bittner** [comment] 2017-11-05 19:59
@nls1729 Can you quote the source of your "remove the hot corner" investigation? - I've installed the [Gnome Tweak Tool](https://wiki.gnome.org/action/show/Apps/GnomeTweakTool), activated "Activities Overview Hot Corner", and the activities overview shows when I move the mouse to the top left corner.

Why Not Make It Work For Both Worlds?
-----------------
Can you guide us to where the application exception occurs when the related error happens? (The one that lets the [extension website](https://extensions.gnome.org/extension/358/activities-configurator/) show the red "ERROR" button and the Gnome Tweak Tool the warning triangle in Extensions.)

We could try to handle the exceptions and cater for both cases, the vanilla Gnome and Canonical's Ubuntu implementation. A robust implementation like that would be helpful.

**Comment by nls1729** [comment] 2017-11-06 20:42
> @nls1729 Can you quote the source of your "remove the hot corner" investigation? - I've installed the Gnome Tweak Tool, activated "Activities Overview Hot Corner", and the activities overview shows when I move the mouse to the top left corner.

Source?

I extracted the javascript code from the gresources in the Gnome Shell Ubuntu library and examined layout.js and confirmed the patch in bug 688320 had been implemented as shown in the bug report.

See < https://didrocks.fr/2017/08/18/ubuntu-gnome-shell-in-artful-day-5/ >
See < https://bugzilla.gnome.org/show_bug.cgi?id=688320 >.

The patch provides a global setting which can be used to disable/enable the hot corners.  When the setting is enabled the hot corners are created. When the corners are disabled the corners are not created (Ubuntu Session setting default) which means the hot corner is effectively removed from the shell session to disable it.  As you can see in my comments in the bug report I would prefer disabling by a means which would not cause errors for extensions dependent upon the hot corner.

The Tweak Tool provided by Ubuntu has been modified to access the global setting to disable/enable the hot corner.  The patch referred to in bug 688320 has not been added to the upstream Gnome Shell. It was applied by Ubuntu developers downstream. The upstream Tweak Tool has a commit to update the tool to handle the global setting but as of now is commented out.

See < https://git.gnome.org/browse/gnome-tweak-tool/commit/?id=29073dd8a70e577bfada31861588eb766fd86928 >. 

The Ubuntu developers have modified the Tweak Tool source to provide the functionality in the commit.

See <  https://launchpad.net/ubuntu/artful/+source/gnome-tweak-tool/+changelog >.
See /usr/lib/python3/dist-packages/gtweak/tweaks/tweak_group_top_bar.py line 79.  

> Why Not Make It Work For Both Worlds?
> Can you guide us to where the application exception occurs when the related error happens? (The one that lets the extension website show the red "ERROR" button and the Gnome Tweak Tool the warning triangle in Extensions.)

Who is us?

When the website installs the extension the error occurs when the extension is enabled due to references to the hot corner which are undefined.  In the Ubuntu Session if you enable the hot corner with the Tweak Tool before installing the extension no error occurs.

I am currently working on code to detect the Ubuntu Session and not produce the "ERROR". The change is if the hot corner is disabled notify the user the hot corner must be enabled with the Tweak Tool to use the Activities Configurator extension. The user need only enable the hot corner and restart the session to use the extension.   I could simply enable the hot corners in the extension, but it is my understanding the Ubuntu developers requested the patch and set the setting to false (disable) to be the default for the Ubuntu Session.  I think the user should not be bypassed.   

> We could try to handle the exceptions and cater for both cases, the vanilla Gnome and Canonical's Ubuntu implementation. A robust implementation like that would be helpful.

Who is we?

I have tested the extension under the Ubuntu Session.  Some of the extensions settings (Panel Shadow) cause minor cosmetic issues in the Ubunbu Session.  With the Dock and the Ubuntu Session theme I don't see a reasonable solution except if the user thinks it looks bad don't use the shadow setting.

I will close this issue when the updated extension is available on extensions.gnome.org.

**Comment by Maestroschan** [comment] 2017-11-06 21:16
> Who is we?

Don't be so cold, i think he just wanted to contribute

**Comment by nls1729** [comment] 2017-11-12 22:58
The updated extension has been uploaded for review. See https://nls1729.github.io/activities_config.html Under Construction.

**Comment by nls1729** [comment] 2017-11-17 22:58
Activities Configurator version 60 is now available at:
https://extensions.gnome.org/extension/358/activities-configurator
This version is compatible with Ubuntu 17.10.
I will leave this issue open for a while for comments or questions.

**Closed** 2017-12-03 22:44 UTC
