### ISSUE TITLE
Do Not Disturb Button's panel icon is maybe misleading.

### ISSUE THREAD

**Issue by terrycloth** [nls1729/acme-code#22] opened 2017-03-29 19:52 UTC
The Do Not Disturb Button description specifies that it does not integrate with the "available" status for chat applications in Online Accounts. Moreover, DNDB hides *all* system notifications, not just chat messages.

GNOME Shell includes an icon that appears in the notification area when there are no notifications or calendar events to display. It's pretty similar, but I think the placement of the stem might better evoke "notification" than "chat message". The SVG version should exist on your system at `/usr/share/icons/gnome/scalable/apps/preferences-system-notifications-symbolic.svg`.

![screenshot from 2017-03-29 11-49-09--cropped](https://cloud.githubusercontent.com/assets/3881885/24472239/dd730e34-1479-11e7-83a8-79570060aa28.png)

Otherwise, the usual imagery for a generic notifications icon (as opposed to an error or warning message icon) is probably a bell. [OpenClipArt has examples of both bells and balloons](https://openclipart.org/search/?query=notification) as notification icons.

**Comment by nls1729** [comment] 2017-04-02 21:13
I did some research into the use of the balloon to indicate notifications.  It seems very common for software documentation to refer to a "notification balloon"  for use in displaying popup messages. I agree the shape of the icons I used is probably associated with the chat apps that were previously connected to earlier versions of the shell.  My mention of the DNDB not being integrated was an attempt to prevent confusion with the integration of chat apps and the shell prior to version 3.16.   The DNDB extension does prevent display of all notifications in the banner with the exception of those flagged as critical by design (per the user request).

![available-yes](https://cloud.githubusercontent.com/assets/2984166/24590638/aa600cca-17be-11e7-991d-eff1e1fbdf9f.png)
![available-no](https://cloud.githubusercontent.com/assets/2984166/24590640/b6feafc2-17be-11e7-82e1-670d71cc359c.png)
I need to represent two states so I created the above icons with a balloon in the style of the No Notifications icon.  I think the icons being more consistent with the No Notifications icon should lessen any confusion.  I found the No Notifications icon displayed in the calendar notification area actually comes from the shell theme compiled gresource file and is named no-notifications.svg.

Let me know what you think.  I will update the extension if you think the icon change satisfies your concerns.

**Comment by terrycloth** [comment] 2017-04-03 08:34
Yeah, those look great. It's a subtle but important difference, I think.

Thanks for indulging my nitpicks 🙂

**Comment by nls1729** [comment] 2017-04-05 19:05
The Do Not Disturb Button is in queue for review on extensions.gnome.org.  I will close this issue as soon as it is accepted.

**Comment by nls1729** [comment] 2017-04-06 11:03
Both the Do Not Disturb Button and the Activities Configurator extensions have new versions accepted on extensions.gnome.org.  The Activities Configurator had a bug when run under GS3.24 which I cleared.  Both extensions have been tested under Fedora 26 alpha GS3.24.

If you haven't seen the following post on the Fedora Desktop Mailing List you may find it of interest.
https://lists.fedoraproject.org/archives/list/desktop@lists.fedoraproject.org/thread/VGEHR4BUSTNCQEG7BICHVVEAW2AC4YCN/

**Closed by nls1729** 2017-04-06 11:03 UTC
