### ISSUE TITLE
Disable hot corner functionality quits working after reboot

### ISSUE THREAD

**Issue by KeithCu** [nls1729/acme-code#8] opened 2016-03-28 03:48 UTC
I installed this great plugin recently mostly to disable the activities hot corner. It works great, but after a reboot the hot corner starts activating again. Note: I've seen this on two different up-to-date Arch Linux machines.

If I go and toggle the slider twice, then it starts working again, but I thought I'd file a bug.

Here is a bit more info which may be helpful:
I'm running Gnome classic shell, and the only other non-default settings I have are to disable the activities button and I hide the icon.

**Comment by nls1729** [comment] 2016-03-28 19:02
Hello Keith,

First I need a bit of information.
What version of Gnome Shell are you using?
Where did you get the extension (extensions.gnome.org, github, other)?

FYI the latest version of the extension is always available at extensions.gnome.org.
Any bug fixes or new features are done using my local git repo and uploaded to the ego site
for review.  When the review is completed and the extension is available for users on ego I
push the changes to github.

Would you be willing to test for me if I  provide you a patch or a zip-file with a possible fix for your problem?

Thanks for you bug report.
Norman

**Comment by KeithCu** [comment] 2016-03-28 21:52
Hi Norman,

Both machines are running Gnome 3.18. I got the extension from extensions.gnome.org.

Sure, I'd be happy to test something. However, I would need help to manually install it as all I did originally was click on things on the website.

**Comment by nls1729** [comment] 2016-03-29 10:14
Hello,
The problem is when the Classic mode is used the Applications Menu conflicts with the extension and over-writes the code installed by the extension to disable the hot corner.  I made a small change to the
extension to detect the Classic mode and enable the Conflict Detection preference.  This allows the extension to repair the damage.  It does not affect the Applications Menu.  I will include this fix in the next release of the extension.  I have attached instructions and a zip-file.  Let me know how it goes.

[instructions.txt](https://github.com/nls1729/acme-code/files/193235/instructions.txt)
[activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/193236/activities-config.nls1729.zip)

**Comment by KeithCu** [comment] 2016-03-29 22:02
Hi Norman,

Thanks for the test build and instructions! I've got it installed. It seems to be working fine so far but I sometimes have to wait a couple of days. The only thing I noticed is that the top menu bar is now faded. I'm including a screen shot. Note, I haven't fiddled with any settings that might cause this.
![screenshot from 2016-03-29 17-58-28](https://cloud.githubusercontent.com/assets/662157/14125232/0f957904-f5d8-11e5-8710-1dd4248b443b.png)

**Comment by nls1729** [comment] 2016-03-30 11:54
There are two solutions to the dark shadow problem you observed.  One solution is to set the background color to white and transparency of the panel to zero and the window max effect to no effect with the extension's preferences.  The other is to change the code to ignore panel background settings when in classic mode with the default classic theme.  My thinking is most classic mode users want to use the mode for its simplicity.  What do you think?  Please try the second solution attached.  Let me know how it goes.

[activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/195407/activities-config.nls1729.zip)

**Comment by KeithCu** [comment] 2016-03-30 12:16
I tried out your latest version and my panel looks great again. Thank you. I think you could just have an option to ignore the color settings and turn it on by default. You don't necessarily need to disable the feature entirely, but try to have it look good out of the box.

**Comment by nls1729** [comment] 2016-04-08 18:45
Hello Keith,
Version 44 of the Activities Configurator extension is available on the ego web site.  I added an option to enable the override of a user theme or the Classic Mode theme.  Essentially if a user logs into Classic Mode or installs a User theme the extension does not apply the preferences that affect the appearance of the panel unless the user sets the override to ON.  I am closing this issue.  If you have any trouble with the new version let me know.
Regards,
Norman

**Closed by nls1729** 2016-04-08 18:45 UTC
