### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by ryanvade** [nls1729/acme-code#3] opened 2015-06-27 02:45 UTC
It seems that Activities Configurator has some memory leak issues if you let it run for greater than 24 hours.

**Comment by nls1729** [comment] 2015-06-27 10:40
Memory leaks are a bad thing. They occur usually at a much lower level than in software written in a scripting language.  But since you  have found evidence of a memory leak I certainly want to find it.

I  will need more information to address the issue.  If I can duplicate your execution environment and reproduce the problem it can be fixed.

0.1 What version of the Activities Configurator?
0.2 Was the  Activities Configurator installed from extensions.gnome.org?
0.3 If not extensions.gnome.org, where?

1. What is the Linux distribution?
2. What version of the Gnome Shell?
3. Does the leak occur if the only enabled extension is the Activities Configurator?
4. Is Conflict Detection enabled?
5. What are you using to measure the memory leak, top,  or an actual diagnostic tool?
6. Have you looked at the code and have any ideas about where there might be a problem? 

If needed would you be willing to run a version of the extension with diagnostic code?
This would only be necessary if I can't duplicate the problem.

For the most part the Activities Configurator doesn't do anything.  It doesn't (or it shouldn't).

Thanks for your heads up.

**Comment by ryanvade** [comment] 2015-06-27 19:27
Activities Configurator was installed from extensions.gnome.org
Manjaro Linux
Gnome 3.16.2
It seems like the memory leaks only occur when using this shell extension yes.  I am going to test some more to confirm. 
I believe conflict detection is enabled.

I get a message when using the extension for an extended period about a lack of memory which goes away after disabling the extension or restarting GNOME. I will get you more information soon. 

I have looked at your code, at least the parts affecting my settings, and have not found anything that could cause the issue. I am willing to run a debugging version should you need me to. 

This has also been confirmed by a friend of mine who is using a Manjaro remix I made. 
If you want to try that, here is a link:
https://owncloud.ryanvade.info/index.php/s/HNj9yuJFzX7oe6z
https://owncloud.ryanvade.info/index.php/s/rs8Hgpfm2aHMdzt
The above download has the exact environment I am using.

**Comment by nls1729** [comment] 2015-06-27 22:12
I have downloaded your image and will try to setup a test system in the morning.

**Comment by nls1729** [comment] 2015-06-29 12:29
Is there a way to save your image to disk that can be  booted?

How much memory is in the machine that runs out of ram?

From my testing the size of the shell grows with any activity,  extensions enabled or not.  It never seems to return to a significantly smaller size.  I ran tests for about six hours yesterday and will try to setup something more definitive today.

So far I can't find anything in the extension's code where a resource is created and not released, but the shell grows when the overview is displayed whether by code in the extension or shell code when the extension is disabled.   The extension is really just a patch to the shell's code.  Almost all of the real work is done  with code from the shell.

**Comment by ryanvade** [comment] 2015-06-29 18:37
The image is a standard ISO, anything that can be done with an ISO you can do with my image. 

Both his system and my own have 16Gb ram. I have not found anything either so I'm thinking that there has to be a conflict somewhere with another plugin.

**Comment by ryanvade** [comment] 2015-06-30 19:37
Here is the exact error:
![error](https://cloud.githubusercontent.com/assets/1910293/8440070/8fa1c690-1f35-11e5-9fc4-31f7ae07c164.png)

**Comment by nls1729** [comment] 2015-06-30 20:30
I don't see the Activities Configurator in the screen shot.
Was it enabled?
What caused the attempt to execute gnome-shell-extensions-prefs?

**Comment by ryanvade** [comment] 2015-06-30 20:33
It was enabled.  As for gnome-shell-extension-prefs I beleive it was the weather extension. But again, this does not happen if the activites-configurator extension is disabled.

**Comment by nls1729** [comment] 2015-07-08 12:04
I have done many hours of testing and cannot detect a memory leak caused by the extension.  You are definitely seeing what looks like a memory leak if you get the message in the screen shot you provided.  With 16G of memory you can get the message without a memory leak but you would have to have a lot of processes running.  As I have said before the extension is just a patch onto the gnome-shell.  The gnome-shell is written in javascript and uses gobject introspection to access library code written in C. Javascript uses garbage collection to manage memory.  The gnome-shell process will normally grow quite large and then a garbage collection will return it to a smaller size.  When you run gnome-shell-extension-prefs from the weather extension a glib spawn function is called.  A fork() is called which requires the kernel to find enough memory equal to the size of the gnome-shell to create a child process to execute gnome-shell-extension-prefs.  If the memory can't be found the error occurs.  I cover all this to point out that the gnome-shell process simply must grow very large to be a problem.  I monitored the size of the gnome-shell over many hours and saw the grow and garbage collect cycle occur many times and it never appeared to grow as it would if there is a memory leak.  That said it doesn't mean there is not a memory leak somewhere. I tested on three different systems with from 2G to 4G to 8G of memory.  It only means that I haven't been able to create it until I tested with google-chrome.  If you are using google-chrome you should update if you have not done so recently. I think Version 43.0.2357.132 (64-bit) is the current version. There is a long discussion about a memory leak in google-chrome. [ https://productforums.google.com/forum/#!msg/chrome/86yzpxX7aws/4InxVS4zrwgJ ] The screen image you provided shows google-chrome. I was able to get the failure running google-chrome with the extension enabled and also with it completely removed.  If you have Activities Configurator version 35 installed please update to version 36 from the extension website.  I did not see evidence of a memory leak in v35 which was in your iso but v36 has a large number of changes related to translations.  I suspect you are using au english and it may make a difference. You have probably done the following but I'll suggest it anyway if you continue to have memory leak symptoms:

$ while true; do ps xua --sort -rss | cut -c1-120 | head -6; sleep 10; done

You can also do it this way to preserve the results:

$ while true; do ps xua --sort -rss | cut -c1-120 | head -6 >> ~/rss.txt ; sleep 60; done

Also this can be useful:

$ top

type a letter f to get a top Fields list

arrow down to %MEM

type a letter s to change the sort order

type a letter q to return to the top display

**Comment by nls1729** [comment] 2015-07-21 15:19
Closed as no trouble found.

**Closed by nls1729** 2015-07-21 15:19 UTC
