### ISSUE TITLE
Activities Configurator - Randomly reenable hot corners 

### ISSUE THREAD

**Issue by mezcalbert** [nls1729/acme-code#73] opened 2020-05-08 15:24 UTC
Hi,

I installed this extension recently, but it's pretty invasive and annoying.

1. There's a big pop-up sometimes asking to enable hot corners, it's almost impossible to get rid of it (clicking on close doesn't work) and the background is quite dark, you can barely see behind it, hence activate hot corners to make that pop-up go away.

2. **Almost every time Gnome Shell is refreshed or restarted (adding a second monitor, starting Gnome, alt+f2+r, etc...), hot corners are enabled again.**

I hate hot corners as much as I have no use of the activities overview. I don't understand why this extension is forcing people so hard to enable them! It's a choice we should make for ourselves.

Is it really mandatory to force hot corners when you just need to change the displayed name "Activities" into a different word?

**Comment by nls1729** [comment] 2020-05-10 11:27
This problem has been reported before.  It was caused  by another extension which needs the hot corner to function.  If changing the text to a different string is stopping the problem I would really appreciate if you would do some testing and hopefully find the other extension which is the bad actor.  It is also possible the linux distribution you are using has a problem. First I have questions.

1.  What linux distribution and version are you using?

2.  Alt+f2+r, why are you not using Wayland?

3.  Are you using a laptop?

Please perform the following procedure:

1.  Change the text back to Activities and hopefully cause the problem to occur.   If you see the pop-up record exactly what it is says and let me knows what it is.

2.  Disable all extensions except the Activities Configurator.

3.  Power the system down and then power it up.

4.  Does the problem continue to occur?

5.  If the answer is NO the problem is with one or more of the extensions and continue with step 6.
If the answer is YES let know we will need a different procedure.

6.  Enable one of the disabled extensions.  Log out and then login.  If the problem does not occur got back to step 6 and enable another extension.  If problem occurs. Write down the extension's name. Disable the extension you just enabled.  Log out and then login.  Go back to step 6.

**Comment by mezcalbert** [comment] 2020-05-17 01:25
1. Ubuntu 20.04
2. Because it's not ready. I have at least 10 different issues with it. Not being able to refresh it with alt + f2 when it's quickly consuming too much RAM or an issue pops up is definitely one.
3. Both a desktop and a laptop. Configured very much alike. And same issue.

I have 15 other extensions installed to get something out of Gnome, otherwise it's worthless to my workflow. Vanilla Gnome is really limited. I'm really sorry but your procedure is way too time consuming in this context. Especially since Activities configurator reenabling the hot corner is a random feat. Adding a second monitor, starting Gnome (reboot or log out), alt+f2+r, etc... does trigger it, but not every time.
All of these 15 other extensions work great together. No weird interactions. No issues. No hot corner acting up.
If I remove Activities Configurator, I have no issue whatsoever.

I can give you my extensions list though (in case you can detect a pattern with feedback you got previously):
- Activities Configurator
- Caffeine
- Dash-to-Dock
- Frippery Move CLock
- GSConnect
- Mpris Indicator Button
- Multi Monitors Add-On
- Onboard Indicator
- OpenWeather
- Panel OSD
- Sound Input & Ouput Device Chooser
- Syspeek-GS
- TopIcons Plus
- Ubuntu Appindicators
- Unite
- User Themes

If I had a guess, I would say Unite might have some overlap with your extension. And Gnome Tweaks as well.

**Comment by mezcalbert** [comment] 2020-06-09 22:22
I've installed the "no topleft hot corner" extension and it works reliably ever since. It's a bit sad that I needed yet another extension to bypass Gnome limitations, but at least that's an invading and irritating problem gone.

It's more of a "worked around" than a "solved" so I'll let you decide if you close it as I won't investigate the matter further.

Thanks for taking the time to reply!

**Comment by nls1729** [comment] 2020-06-09 22:56
Extension conflicts are very hard to solve.  The order extensions are enabled is an attempt by the shell to prevent conflicts.  Since one extension can over-write part of another and it can be over-written by its abuser is a big problem.  It's the nature of patching code.  I am glad you found something you can "live with".  The Activities Configurator has several  functions that try to co-operate with other extensions but it is very difficult to be sure they will work.  I will close the issue.

**Closed by nls1729** 2020-06-09 22:56 UTC
